import PageName from "@/app/(admin)/assets/components/PageName"
import AdminsTable from "./components/AdminsTable"



export const metadata = {
    title: 'Admins',
    description: "Generated by create next app",
}



export default function ManageAdminsPage() {
    return (
        <div className="flex flex-col gap-4">
            <PageName pageName='Admins' />
            <AdminsTable />
        </div>
    )
}

