const global_key = process.env.NEXT_PUBLIC_GLOBAL_KEY

export const metadata = {
    title: {
        default: `This is untitled ${global_key} system page`,
        template: `${global_key} | %s`
    },
    description: "Generated by create next app",
}





export default function RootLayout({ children }) {
    return (
        <>
            {/* <PageLoadingProgressBar /> */}
            {children}
        </>
    );
}
