import PageName from "@/app/(admin)/assets/components/PageName";
import AnalyticsContainer from "./components/AnalyticsContainer";


const global_key = process.env.GLOBAL_KEY


export const metadata = {
    title: `Analytics`,
    description: "Generated by create next app",
}






export default function AnalyticsPage() {
    return (
        <div className="flex flex-col gap-4">
            <PageName pageName='Analytics' />
            <AnalyticsContainer />
        </div>
    )
}
