import PageName from "@/app/(admin)/assets/components/PageName"
import CustomersTable from "./components/CustomersTable"



export const metadata = {
    title: 'My customers',
    description: "Generated by create next app",
}



export default function Customers() {
    return (
        <div className="flex flex-col gap-4">
            <PageName pageName='My customers' />
            <CustomersTable />
        </div>
    )
}

