import { Toaster } from "sonner";
import "./globals.css";
import { NextUIProvider, Spinner } from "@nextui-org/react";
import Children from "./Children";
import PageLoadingProgressBar from "./assets/components/PageLoadingProgressBar";
import { CheckMarkCircleIcon, CyrcleXMarkIcon } from "@/constants/Icons";
import { cn } from "@/lib/utils";
import { cookies, headers } from "next/headers";
// import { NextIntlClientProvider } from "next-intl";


// import { getMessages } from 'next-intl/server'



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        media: '(prefers-color-scheme: light)',
        url: '/favicon-dark.svg',
        href: '/favicon-dark.svg',
      },
      {
        media: '(prefers-color-scheme: dark)',
        url: '/favicon.svg',
        href: '/favicon.svg',
      },
    ],

  },
}




export default async function RootLayout({ children }) {
  // const messages = await getMessages()
  var themeCookie = headers().get('cookie')?.match(/theme=([^;]+)/)?.[1] || 'light' // Default to 'light' theme

  themeCookie = 'dark'



  return (
    <html lang={'en'}>

      <body>
        <NextUIProvider>
          <main className={cn(`text-foreground bg-background`, themeCookie)}>
            {/* <main className="light text-foreground bg-background"> */}

            <Children>
              <PageLoadingProgressBar />

              {children}
            </Children>
            <Toaster position="bottom-right" />






            {/* Spinners || Statuses */}
            <div id="loading--status" className={cn('bg-light-1 p-2 rounded-xl shadow-xl flex items-center justify-center absolute top-0 z-50 left-1/2 -translate-x-1/2 -translate-y-full transition-all'
            )
            }>
              <Spinner size="sm" color="default" />
            </div>




            {/* Success  */}
            <div id="success--status" className={cn('bg-light-1 text-green-700 p-2 rounded-xl shadow-xl flex items-center justify-center absolute top-0 z-50 left-1/2 -translate-x-1/2 -translate-y-full transition-all'
            )}>
              <CheckMarkCircleIcon />
            </div>



            {/* Error  */}
            <div id="error--status" className={cn('bg-light-1 text-red-700 p-2 rounded-xl shadow-xl flex items-center justify-center absolute top-0 z-50 left-1/2 -translate-x-1/2 -translate-y-full transition-all'
            )}>
              <CyrcleXMarkIcon />
            </div>
          </main>

        </NextUIProvider>
      </body>
    </html>

  );
}
