// "use client"
import { NextIntlClientProvider, useLocale } from 'next-intl';
import { getMessages } from 'next-intl/server';
import UserAccountProvider from './provider';




const global_key = process.env.NEXT_PUBLIC_GLOBAL_KEY

export const metadata = {
    title: {
        default: `This is untitled ${global_key} customer page`,
        template: `${global_key} | %s`
    },
    description: "Generated by create next app",
}



export default async function UserAccountLayout({ children }) {
    // side is the easiest way to get started
    const messages = await getMessages()

    return (
        <NextIntlClientProvider messages={messages}>
            <UserAccountProvider>
                {children}
            </UserAccountProvider>
            {/* <main className="flex relative h-[100vh]">
                <div className="page-content w-full flex flex-col h-full overflow-hidden" dir={'rtl'}>
                    <Header />
                    <main className="p-5 bg-light-2 dark:bg-dark-2 overflow-y-auto h-full flex-1 ">
                        <div className="flex justify-center items-center mx-auto">
                            {children}
                        </div>
                    </main>
                </div>
            </main> */}
        </NextIntlClientProvider>
    )
}
