"use client"
import axios from 'axios';
import { useEffect, useState } from 'react';

import { cpe_api } from '@/constants/_api';

import PageName from "@/app/(admin)/assets/components/PageName";
import SchoolsTable from "./components/SchoolsTable";
import TableSkeleten from '@/app/assets/components/TableSkeleten';


// const metadata = {
//   title: "Schools page",
//   description: "Generated by create next app",
// }

export default function Schools() {
  const [loading, setLoading] = useState(true);
  const [schools, setSchools] = useState([])

  useEffect(() => {
    const fetchData = async () => {
      setLoading(true);
      try {
        const { data: response } = await axios.get(`${cpe_api}?target=schools`);
        setSchools(response);
        // console.log(response);

      } catch (error) {
        console.log(error.message);
      } finally {
        setLoading(false);
      }
    }

    fetchData();
  }, []);


  return (
    <div className="flex flex-col gap-4">
      <PageName pageName='Schools' />
      {loading &&
        <TableSkeleten />
      }

      {!loading && (
        <SchoolsTable schools={schools} />
      )}
    </div>
  )
}

